version: '3.7'
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      API_HOST: web
      API_PORT: 8080
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: users_crud
    depends_on:
      - db
    networks:
      - users-crud-network
    command: npm run start
  db:
    image: mongo
    restart: always
    volumes:
      - data-volume:/data/db
    ports:
      - 27100:27017
    networks:
      - users-crud-network

networks:
  users-crud-network:
      driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
