version: '3.7'

services:
    server:
        build: ./server
        image: users-crud-server-image
        container_name: users-crud-server
        command: npm run start:dev
        volumes:
            - ./server/:/usr/src/app
            - /usr/app/node_modules
        environment: 
            - DB_HOST=db
            - DB_PORT=27017
            - DB_NAME=users_crud
        ports: 
            - 8080:8080
        depends_on: 
            - db
        networks: 
            - users-crud-network
    db:
        image: mongo
        restart: always
        ports:
            - 27100:27017
        networks: 
            - users-crud-network

networks:
    users-crud-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
